language: python
python:
  - "3.8"
sudo: required

services:
  - docker
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: apisimplon
 

deploy:
  provider: script
  script: 
    # docker push cisaia/apisimplon;

    # docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:push web --app $HEROKU_APP_NAME
    heroku container:release web --app $HEROKU_APP_NAME
  on:
    branch: master