language: python
python:
  - "3.8"
sudo: required

services:
  - docker

before_install:

script:
    - echo 'foo'

deploy:
    provider: heroku
    api_key: $HEROKU_TOKEN
    app : apilucile1
    skip_cleanup: True